apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubenetroutedelay
  namespace: kube-system
  labels:
    k8s-app: kubenetroutedelay
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubenetroutedelay
  labels:
    k8s-app: kubenetroutedelay
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubenetroutedelay
  labels:
    k8s-app: kubenetroutedelay
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubenetroutedelay
subjects:
- kind: ServiceAccount
  name: kubenetroutedelay
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubenetroutedelay-probe
  namespace: kube-system
  labels:
    k8s-app: kubenetroutedelay
    tier: probe
spec:
  selector:
    matchLabels:
      k8s-app: kubenetroutedelay
      tier: probe
  template:
    metadata:
      labels:
        k8s-app: kubenetroutedelay
        tier: probe
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
        # kubernetes.azure.com/mode: system
        agentpool: foobar
      containers:
      - name: probe
        image: tdihp/kubenetroutedelay:latest
        args: ["probe", "-n", "$(NODE_NAME)"]
        resources:
            requests:
              cpu: 100m
              memory: 100M
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      serviceAccountName: kubenetroutedelay
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenetroutedelay-watcher
  namespace: kube-system
  labels:
    k8s-app: kubenetroutedelay
    tier: watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kubenetroutedelay
      tier: watcher
  template:
    metadata:
      labels: 
        k8s-app: kubenetroutedelay
        tier: watcher
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
        kubernetes.azure.com/mode: system
      containers:
      - name: probe
        image: tdihp/kubenetroutedelay:latest
        args: ["watcher", "-s", "agentpool=foobar"]  # suppose we are to update the "foobar" agentpool
        resources:
            requests:
              cpu: 100m
              memory: 100M
      serviceAccountName: kubenetroutedelay
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: kubenetroutedelay
        operator: Exists
